### ISSUE TITLE
Heuristic Recomendation Formula

### ISSUE THREAD

**Issue by fcoclavero** [fcoclavero/machinelol#42]
Create a formula which combines player champion stats into a single value, to be used in the heuristic recomendation. System could be made extendable, as to offer the user several options.

**Comment by Vichoko** [comment]
The actual formula is in `\Django\recomendation\_recomendationSystem.py, line 192`. It's a weigthed summatory of champion's WinRate, KDA & Champion Mastery Score.

Se puede cambiar todo.
